apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: candidate-disk
  namespace: omp
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 1Gi